builders:
  prefixes:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["prefixesBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache
  measurement:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["measurementBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache
  interpreter:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["interpreterBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache
  prefix_unit:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["prefixUnitBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache
  prefix_measurement:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["prefixMeasurementBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache
  measurement_per:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["prefixedExtensionBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache
  extension_num:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["numExtensionBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache
  unit:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["unitBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache
  measurement_id:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["measurementIdentifierBuilder"]
    build_extensions: { ".dart": [".measurement"] }
    build_to: cache
  derived_units:
    import: "lib/src/generator/generators/derived_generator.dart"
    builder_factories: ["derivedUnitBuilder"]
    build_extensions: { ".dart": ["lib/src/generated/derived_units.dart"] }
    build_to: source
  library:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["libraryBuilder"]
    build_extensions: { ".measurement": ["lib/src/generated/fling_units.dart"] }
    build_to: source
  prefix_id:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["prefixIdentifierBuilder"]
    build_extensions: { ".dart": [".prefixes"] }
    build_to: cache
  unit_specialization:
    import: "lib/src/generator/generator.dart"
    builder_factories: ["unitSpecializationBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    build_to: cache

targets:
  $default:
    builders:
      fling_units|prefixes:
        options:
          generate_for:
            - lib/src/prefixes/*.dart
      fling_units|measurement_per:
        options:
          generate_for:
            - lib/src/prefixes/*.dart
      fling_units|measurement:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|interpreter:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|prefix_unit:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|prefix_measurement:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|extension_num:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|unit:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|unit_specialization:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      source_gen|combining_builder:
        options:
          build_extensions:
            {
              "^lib/src/measurements/{{}}.dart":
                ["lib/src/generated/{{}}.dart"],
              "^lib/src/prefixes/{{}}.dart": ["lib/src/generated/{{}}.dart"],
            }
      fling_units|derived_units:
        options:
          max: 3
      fling_units|measurement_id:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|prefix_id:
        options:
          generate_for:
            - lib/src/prefixes/*.dart
      fling_units|library:
        options:
          generate_for:
            - lib/src/measurements/*.dart
