builders:
  prefixes:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["prefixesBuilder"]
    build_extensions: {".dart": [".g.part"]}
    build_to: cache
  measurement:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["measurementBuilder"]
    build_extensions: {".dart": [".g.part"]}
    build_to: cache
  interpreter:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["interpreterBuilder"]
    build_extensions: {".dart": [".g.part"]}
    build_to: cache
  prefix:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["prefixBuilder"]
    build_extensions: {".dart": [".g.part"]}
    build_to: cache
  extension:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["extensionBuilder"]
    build_extensions: {".dart": [".g.part"]}
    build_to: cache
  unit:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["unitBuilder"]
    build_extensions: {".dart": [".g.part"]}
    build_to: cache
  measurement_prefix:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["measurementPrefixBuilder"]
    build_extensions: {".measurement": ["lib/src/generated/prefix.dart"]}
    build_to: source
    required_inputs: [".measurement"]
  measurement_id:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["measurementIdentifierBuilder"]
    build_extensions: {".dart": [".measurement"]}
    build_to: cache
  library:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["libraryBuilder"]
    build_extensions: {".measurement": ["lib/src/generated/fling_units.dart"]}
    build_to: source
  prefix_id:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["prefixIdentifierBuilder"]
    build_extensions: {".dart": [".prefixes"]}
    build_to: cache
  visitor:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["visitorBuilder"]
    build_extensions: {".measurement": ["lib/src/generated/visitor.dart"]}
    build_to: source
    required_inputs: [".measurement"]
  num_extension:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["numExtensionBuilder"]
    build_extensions: {".measurement": ["lib/src/generated/extension.dart"]}
    build_to: source
    required_inputs: [".measurement"]
  derived:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["derivedBuilder"]
    build_extensions: {".measurement": ["lib/src/generated/derived.dart"]}
    build_to: source
    required_inputs: [".measurement", ".prefixes"]
  square:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["derivedSquareBuilder"]
    build_extensions: {".measurement": ["lib/src/generated/square.dart"]}
    build_to: source
    required_inputs: [".measurement", ".prefixes"]
  cubic:
    import: "package:fling_units/generator/generator.dart"
    builder_factories: ["derivedCubicBuilder"]
    build_extensions: {".measurement": ["lib/src/generated/cubic.dart"]}
    build_to: source
    required_inputs: [".measurement", ".prefixes"]

targets:
  $default:
    builders:
      fling_units|prefixes:
        options:
          generate_for:
            - lib/src/prefixes/*.dart
      fling_units|measurement:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|interpreter:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|prefix:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|extension:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|unit:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      source_gen|combining_builder:
        options:
          build_extensions: {"^lib/src/measurements/{{}}.dart": ["lib/src/generated/{{}}.dart"],"^lib/src/prefixes/{{}}.dart": ["lib/src/generated/{{}}.dart"]}
      fling_units|measurement_id:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|prefix_id:
        options:
          generate_for:
            - lib/src/prefixes/*.dart
      fling_units|measurement_prefix:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|library:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|visitor:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|num_extension:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|derived:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|square:
        options:
          generate_for:
            - lib/src/measurements/*.dart
      fling_units|cubic:
        options:
          generate_for:
            - lib/src/measurements/*.dart