name: fling_units
description: Type-safe Dart unit conversion library.
version: 0.1.0
homepage: https://bitbucket.org/gelbermungo/fling-units
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4