name: fling_units
description: Dependency-free, type-safe Dart unit conversion library. Decouple specific unit types you need to work with from the rest of your code.
version: 2.0.2
homepage: https://bitbucket.org/mongoose13/fling-units/wiki/Home
repository: https://bitbucket.org/mongoose13/fling-units/src
issue_tracker: https://bitbucket.org/mongoose13/fling-units/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
