name: fling_units
description: Dependency-free, type-safe Dart unit conversion library. Decouple specific unit types you need to work with from the rest of your code.
version: 3.0.1
homepage: https://bitbucket.org/mongoose13/fling-units/wiki/Home
repository: https://bitbucket.org/mongoose13/fling-units/src
issue_tracker: https://bitbucket.org/mongoose13/fling-units/issues
topics:
  - converter
  - tool
  - unit-converter
  - units

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  analyzer: ^7.2.0
  build: ^2.4.1
  build_runner: ^2.4.8
  code_builder: ^4.10.0
  dart_style: ^3.0.1
  glob: ^2.1.3
  lints: ^5.1.1
  pub_semver: ^2.1.5
  source_gen: ^2.0.0
  test: ^1.22.1
