name: fling_units
description: Dependency-free, type-safe Dart unit conversion library. Decouple specific unit types you need to work with from the rest of your code.
version: 0.2.1
homepage: https://bitbucket.org/gelbermungo/fling-units
repository: https://bitbucket.org/gelbermungo/fling-units/src

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4