name: fling_units
description: Dependency-free, type-safe Dart unit conversion library. Decouple specific unit types you need to work with from the rest of your code.
version: 3.0.0
homepage: https://bitbucket.org/mongoose13/fling-units/wiki/Home
repository: https://bitbucket.org/mongoose13/fling-units/src
issue_tracker: https://bitbucket.org/mongoose13/fling-units/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^3.0.0
  test: ^1.22.1
  analyzer: ^6.4.1
  build: ^2.4.1
  code_builder: ^4.10.0
  source_gen: ^1.5.0
