def execute(command)
  puts command
  exec(command)
end

def silent(command)
  `#{command}`
end

desc "Build measurement classes from configs"
task "gen:build".to_sym do
  execute "dart run build_runner build"
end

desc "Clean up autogenerated measurement files"
task "gen:clean".to_sym do
  silent "rm lib/src/*/*.part"
  silent "rm lib/src/*/*.measurements"
end

desc "Delete autogenerated measurement files"
task "gen:wipe".to_sym do
  execute "dart run build_runner clean"
end

desc "Validate all linters and style checkers"
task "verify".to_sym do
  execute "dart analyze"
  execute "pana ."
end